INSERT INTO `questions` (`question`, `countdown`, `category`, `answers`, `correctAnswer`) VALUES
('What is the main ingredient of omelette?', 30, 1, 'Butter|Cheese|Egg|Milk', 'Egg'),
('Who is the lead singer of Duran Duran?', 30, 1, 'Boy George|Marc Almond|Simon Le Bon|Tony Hadley', 'Simon Le Bon'),
('What is cherry blossom known as in Japanese?', 30, 1, 'Sakura|Samurai|Sudoku|Sumach', 'Sakura'),
('How many keys does a modern piano have?', 60, 1, '85|86|87|88', 'Sakura'),
('What was the name of Anne Boleyn\'s sister?', 45, 1, 'Elizabeth|Jane|Mary|May', 'Mary'),
('In a rainbow, what colour is the outer part of the arch?', 45, 1, 'Orange|Red|Violet|Yellow', 'Red'),
('In Greek and Roman mythology, a multi-headed hound which guards the gates of Hades is called what?', 30, 1, 'Barabas|Cerberus|Gnasher|Pluto', 'Cerberus'),
('What class of submarine was HMS Turbulent?', 45, 1, 'O-class|P-class|R-class|T-class', 'T-class'),
('What is the earliest known writing system in the world?', 60, 1, 'Cuneiform script|Mishnaic Hebrew|Prakrit|Sanskrit', 'Cuneiform script'),
('What nationality was the artist Herge, who created \'The Adventures of Tintin\' series of comic books?', 60, 1, 'Belgian|Dutch|French|German', 'Belgian'),
('Who is the first and only Catholic president of the United States?', 45, 1, 'Dwight D Eisenhower|John F Kennedy|Lyndon B Johnson|Richard Nixon', 'John F Kennedy'),
('Oceans hold what percentage of the Earth\'s surface water?', 30, 1, '67 percent|77 percent|87 percent|97 percent', '97 percent'),
('What are embedded in the sidewalk along Hollywood Boulevard and Vine Street in Los Angeles?', 45, 1, 'Crystals|Lights|Mirrors|Stars', 'Stars'),
('London\'s Ritz Hotel overlooks which park?', 45, 1, 'Green Park|Hyde Park|Regent\'s Park|St James\'s Park', 'Green Park'),
('In Greek mythology, Erebus was the god of what?', 30, 1, 'Darkness|Forests|Mountains|Water', 'Darkness'),
('Miranda is a moon of which planet of the Solar System?', 45, 1, 'Uranus|Mars|Jupiter|Saturn', 'Uranus'),
('Alcatraz Island, once the site of a notorious prison, is situated in which bay?', 30, 1, 'Baffin Bay|Galway Bay|Hudson Bay|San Francisco Bay', 'San Francisco Bay'),
('In what part of the body is the stirrup bone?', 45, 1, 'Ear|Foot|Elbow|Nose', 'Ear'),
('In the Kingsley Amis novel Lucky Jim, the title character is a university lecturer in which subject?', 45, 1, 'English|Geography|History|Maths', 'History'),
('What type of creature is the children\'s animated character Pingu?', 20, 1, 'Penguin|Pelican|Pony|Porcupine', 'Penguin'),
('What was the nickname of the Chicago gangster George Nelson?', 40, 1, 'Baby Face|Cheeky Face|Dog Face|Pig Face', 'Baby Face'),
('St Swithin\'s Day falls on the 15th of which month?', 45, 1, 'April|May|June|July', 'July'),
('According to the song Camptown Races, how long is Camptown racetrack?', 60, 1, 'Two miles|Three miles|Four miles|JuFive milesly', 'Five miles'),
('Which film actor was born Maurice Micklewhite?', 45, 1, 'Michael Caine|Cary Grant|Anthony Hopkins|John Wayne', 'Michael Caine'),
('Which classic novel features the ship The Pequod?', 30, 1, 'The Caine Mutiny|Lord Jim|Moby-Dick|Treasure Island', 'Moby-Dick'),
('What name did Arthur Scargill give to Margaret Thatcher?', 45, 1, 'Plastic Blonde|Plasticine Blonde|Platinum Blonde|Plutonium Blonde', 'Plutonium Blonde'),
('Which of these was not an English railway company?', 60, 1, 'Great Eastern|Great Northern|Great Southern|Great Western', 'Great Southern'),
('In pre-decimal currency, how many florins were there in ten bob?', 45, 1, '2|4|5|10', '5'),
('Which narrative poem by Edgar Allan Poe begins: \'Once upon a midnight dreary\'?', 45, 1, 'The Crow|The Eagle|The Raven|The Vulture', 'The Raven'),
('What type of animal is a Lancashire Heeler?', 45, 1, 'Dog|Goat|Horse|Pig', 'Dog'),
(' In the US, lemon laws are state laws that protect purchasers of faulty what?', 45, 1, 'Cars|Fruit|Refrigerators|TV sets', 'Cars'),
('What was the name of the cloned sheep who made the news in 1996?', 30, 1, 'Dolly|Holly|Molly|Polly', 'Dolly'),
('How is John Manners better known on many English pub signs?', 60, 1, 'The Duke of Cambridge|The Jolly Sailor|The Marquis of Granby|The Woodman', 'The Marquis of Granby'),
('What is the home town of the Dandy comic character Desperate Dan?', 30, 1, 'Cactusville|Cowboyville|Desperateville|Prairieville', 'Cactusville'),
('The name of which Greek letter is used in English to indicate a very small amount?', 30, 1, 'Eta|Iota|Pi|Zeta', 'Iota'),
('Arthur Conan Doyle\'s 1912 novel The Lost World is set in which continent?', 40, 1, 'Africa|Asia|North America|South America', 'South America'),
('What name is given to the wild dogs of Australia?', 30, 1, 'Bingoes|Bongoes|Dingoes|Drongoes', 'Dingoes'),
('In English cuisine, what is a Norfolk swimmer?', 30, 1, 'Cake|Dumpling|Scone|Pie', 'Dumpling'),
('In which year did Princess Anne compete in the Olympic Games?', 30, 1, '1972|1976|1980|1984', '1976'),
('In arithmetic, what name is given to the number below the line in a fraction?', 30, 1, 'Denominator|Numerator|Product|Quotient', 'Denominator'),
('The TORRO scale is used to measure the intensity of what?', 30, 1, 'Earthquakes|Pain|Radiation|Tornadoes', 'Tornadoes'),
('According to the proverb, what is it impossible to find in a haystack?', 20, 1, 'A milkmaid|A needle|A silver lining|A sow\'s ear', 'A needle'),
('Which Dickens character speaks the opening line \'Now, what I want is facts\' in one of the novels?', 30, 1, 'Mr Bumble|Mr Gradgrind|Mr Micawber|Mr Pickwick', 'Mr Gradgrind'),
('What is the title of Vincent van Gogh\'s famous painting of 1885?', 30, 1, 'The Cabbage Eaters|The Onion Eaters|The Potato Eaters|The Sprout Eaters', 'The Potato Eaters'),
('What is the name of the elevated platform used by fashion models to demonstate clothes?', 30, 1, 'Boardwalk|Catwalk|Sidewalk|Walkway', 'Catwalk');
